export const GET_ROUTERS_DETAILS = 'GET_ROUTERS_DETAILS';
export const GET_ROUTERS_DETAILS_SUCCESS = 'GET_ROUTERS_DETAILS_SUCCESS';
export const GET_ROUTERS_DETAILS_ERROR = 'GET_ROUTERS_DETAILS_ERROR';