export const GET_ROUTERS_DETAILS = 'GET_ROUTERS_DETAILS';
export const GET_ROUTERS_DETAILS_SUCCESS = 'GET_ROUTERS_DETAILS_SUCCESS';
export const GET_ROUTERS_DETAILS_ERROR = 'GET_ROUTERS_DETAILS_ERROR';

export const GET_ROUTERS_ACTIONS = 'GET_ROUTERS_ACTIONS';
export const GET_ROUTERS_ACTIONS_SUCCESS = 'GET_ROUTERS_ACTIONS_SUCCESS';
export const GET_ROUTERS_ACTIONS_ERROR = 'GET_ROUTERS_ACTIONS_ERROR';